id: gratis_footer
weight: 0
status: true
uuid: 0a72140a-57d6-4efd-b22b-43d3bada110d
langcode: en
theme: gratis
region: '-1'
plugin: 'system_menu_block:footer'
settings:
  module: system
  admin_label: ''
  label: 'Footer menu'
  label_display: visible
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
