id: useraccountmenu
weight: -3
status: true
uuid: c7ef1a5e-cd75-410a-8a16-2227721268fc
langcode: en
theme: gratis
region: sidebar_second
plugin: 'system_menu_block:account'
settings:
  module: system
  admin_label: ''
  label: 'User account menu'
  label_display: visible
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
