id: userlogin
weight: -2
status: true
uuid: 67d77d6a-9736-4782-a400-e2305d6ebba9
langcode: en
theme: gratis
region: sidebar_second
plugin: user_login_block
settings:
  module: user
  admin_label: ''
  label: 'User login'
  label_display: visible
  cache: -1
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
